### PR TITLE
Add support for xy control

### PR DESCRIPTION
**Pull request by DieKautz**
This PR adds
1. functionality to support fixtures with the xy color mode. It also adds the colorsource control as it is required to switch between temp, rgb and xy color control (see [here](https://developer.dev.casambi.com/#ws-device-xy-color)).
2. Also while using demo.py I found that `BLEDevice.metadata` is deprecated and therefore replaced the call as suggested [here](https://github.com/hbldh/bleak/discussions/1354)

### Known Limitations
- As `colorsource` is an additional control, the consumer (casambi-bt-hass) needs to set this property correctly. (https://github.com/lkempf/casambi-bt-hass/pull/84)
- In a different PR I saw that methods in `Casambi` are used as helpers, e.g. for setting temperature to directly change the attribute of a Unit or Group. How would the exact `OpCode` and binary format be found? Wireshark?

### CODE REVIEW

**Comment by lkempf** [comment]
Sorry that this took so long. I'm having a look now. To get the missing information you either have to look at the debug messages generated by the library  (which dumps all decrypted packages) or use frida to get logs from the app. But I'll see what I can do regarding your questions.

**Comment by lkempf** [comment]
Where did you get the 11 bits from that you use for the XY resolution? I've changed your code to get the length from the unit control but I used the 11 bits for the SetColorXY operation. The resolution in `UnitState` was only needed because I decided against using floats for some reason.

**Comment by lkempf** [comment]
Thanks for the contribution. Looks good to me now (pending a decision on the 11 bit default). Can you easily test my changes? I don't have a fixture available that supports xy or colorsource.

**Comment by DieKautz** [comment]
Hi, thank you for putting your time in!
- Initially 11 bits was a guess from the provided example in the API response https://api.casambi.com/fixture/17716. So trial and error converted `0.247,0.32` to `1036943`
- Setting the color seems to be working. Testing it in homeassistant also works, but there still seems to be a bug with HA receiving the wrong color (Im on `1c9d685`). But that should be discussed in https://github.com/lkempf/casambi-bt-hass/pull/84

From my side this can be merged :+1:

**Comment by lkempf** [comment]
Sorry for the mess (and the wait). The color conversion should be fixed now. Could you test it again?

**Comment by DieKautz** [comment]
I just was able to test it again. Seems to be working just fine now. Thank you for your help!
LGTM

**Pull request merged**
