### PR TITLE
Implement setSlider

### PR DESCRIPTION
**Pull request by michieldwitte**
Tested on:
model='Mito sospeso move up', manufacturer='Occhio'

### CODE REVIEW

**Comment by lkempf** [comment]
I'm not sure that slider will always mean height. Could you give me the unit id for this light? I'd like to check if there is something in the unit specification that indicates that slider means height in that case.

**Comment by michieldwitte** [comment]
Thanks for following up!
This is the information of the device in the network JSON:
```
{
    "deviceID": 1,
    "uuid": "xxxxxxxxxxxxxx",
    "address": "xxxxxxxx",
    "cpu": 1,
    "name": "Mito sospeso move up",
    "type": 16006,
    "appearance": 0,
    "hueID": 0,
    "groupID": 0,
    "position": 0,
    "revision": 1,
    "configRevision": 1,
    "firmware": 11008,
    "modes": [
        {
            "name": "unit_mode1",
            "state": "00ff7f7f00",
            "cycle": true
        },
        {
            "name": "unit_mode2",
            "state": "00007f7f00",
            "cycle": false
        },
        {
            "name": "unit_mode3",
            "state": "00007f7f00",
            "cycle": false
        },
        {
            "name": "unit_mode4",
            "state": "00007f7f00",
            "cycle": false
        }
    ],
    "smartSwitch": {
        "type": 0,
        "id": 0,
        "scenes": [],
        "scenes2": [],
        "group": 0,
        "unit": 0,
        "lingerTime": 120,
        "fadeTime": 10,
        "switchOffFadeTime": 10,
        "switchOffDelayTime": 0,
        "excludeOFF": false,
        "disableDimming": false,
        "presetAction": 32,
        "presetTarget": 0,
        "index": 0
    },
    "pushButtonToggleDisabled": false,
    "linkedSensor": 0,
    "gain": 100.0,
    "startupMode": 0,
    "minOnLevel": 0.0,
    "minLevel": 0.0,
    "maxLevel": 1.0,
    "parameters": [],
    "behaviour": 0,
    "timeout": 0,
    "labels": {},
    "settings": {
        "supportsLongRange": 0.0,
        "cct.minKelvins": 2700.0,
        "cct.maxKelvins": 4000.0
    },
    "details": {},
    "actionConfig": 0,
    "actions": []
}
```
The settings in the application:
Casambi

**Comment by lkempf** [comment]
The control is defined as follows:
`{"type":"slider","name":"$control_pos_h","unit":"cm","offset":32,"length":8,"min":50,"max":200,"default":0,"readonly":false,"valueType":1,"flags":0}`

This means its a custom control and sliders might have different meaning based on model. I'm not sure whether logic required to fully support custom sliders is really necessary (and this would probably necessitate some API changes). However, I think some more logic is needed to detect that a slider is actually a height control. I'm also not quite sure how to determine the correct opcode for height adjustment, but I guess the current one is fine until someone complains about issues with a unit with multiple sliders.

@michieldwitte Do you want to have a go at implementing this (and can you follow my thoughts)? Otherwise I'll take over this PR and will try to get this done for the next release. The infrastructure for supporting additional numerical controls on the HA side is already finished and planned for the next release.

**Comment by lkempf** [comment]
Ok that solution is also fine (and easier). Thanks for your contribution.

**Pull request merged**
